# ----------------------------------------------------------------------------------------------------
#   TODO:  this is a rough cut under development - it's never been run or tested...!
# ------------------------------------------------------------------------------------------------------------------------
# Pipe to deploy Azure Resources Only for multiple environments
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: environments
  type: object
  default: ['DEMO']
- name: dockerFileName
  default: 'src/aks.yaml'

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ each environmentName in parameters.environments }} :
  - stage: CreateInfra${{ environmentName }}
    displayName: Create ${{ environmentName }} Resources
    jobs:
    - template: templates/kube-deploy-template.yml
      parameters:
        environmentName: ${{ environmentName }}
        dockerFileName: ${{ parameters.dockerFileName }}
